# Generated by Django 3.0.8 on 2020-07-27 08:52

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('organization_type', models.CharField(choices=[('1', 'Primary/Secondary School'), ('2', 'University'), ('3', 'Corporate'), ('4', 'Other')], max_length=4)),
                ('organization_name', models.CharField(max_length=125)),
                ('position', models.CharField(blank=True, max_length=125, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizCopy1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(blank=True, default='Quiz title', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, default=4, max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizCopy2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(blank=True, default='Quiz title', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, default=4, max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(blank=True, choices=[('1', 'Admin'), ('2', 'Teacher'), ('3', 'Student')], default=1, max_length=1)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('1', 'Activate'), ('2', 'Block'), ('3', 'Maintenance')], default=1, max_length=1)),
                ('room_name', models.CharField(default='Room Default', max_length=255)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.CharField(max_length=10)),
                ('percent', models.CharField(max_length=10)),
                ('finish_at', models.DateTimeField()),
                ('quiz_copy_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuizCopy2')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quiz_title', models.CharField(blank=True, default='Quiz title', max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('grade', models.CharField(blank=True, default=4, max_length=1)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Room')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuizCopy2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.TextField(choices=[('1', 'MultipleChoice'), ('2', 'TrueFalse'), ('3', 'ShortAnswer')], max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('explain', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('choice', models.TextField()),
                ('correct_choice', models.TextField()),
                ('quiz_copy_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuizCopy2')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionQuizCopy1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_type', models.TextField(choices=[('1', 'MultipleChoice'), ('2', 'TrueFalse'), ('3', 'ShortAnswer')], max_length=1)),
                ('description', models.CharField(max_length=255)),
                ('explain', models.TextField(null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('choice', models.TextField()),
                ('correct_choice', models.TextField()),
                ('quiz_copy_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.QuizCopy1')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DetailResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('choice_answer', models.TextField()),
                ('correct_choice', models.TextField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quiz.Result')),
            ],
        ),
    ]
