# Generated by Django 3.0.8 on 2020-08-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'Primary/Secondary School'), ('2', 'University'), ('3', 'Advance'), ('4', 'Other')], default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizcopy1',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'Primary/Secondary School'), ('2', 'University'), ('3', 'Advance'), ('4', 'Other')], default=4, max_length=1),
        ),
        migrations.AlterField(
            model_name='quizcopy2',
            name='grade',
            field=models.CharField(blank=True, choices=[('1', 'Primary/Secondary School'), ('2', 'University'), ('3', 'Advance'), ('4', 'Other')], default=4, max_length=1),
        ),
    ]
