# Generated by Django 3.0.8 on 2020-08-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0006_auto_20200814_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizcopy1',
            name='quiz_id',
            field=models.IntegerField(default=100),
        ),
    ]
